openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/accounts":
    get:
      tags:
      - account-controller
      operationId: getAll
      responses:
        '200':
          description: "Successfully retrieved list of accounts"
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/AccountResponse"

  "/accounts/{accountId}":
   get:
     tags:
     - account-controller
     operationId: getById
     parameters:
     - name: accountId
       in: path
       required: true
       schema:
         type: integer
         format: int64
     responses:
       '200':
         description: "Successfully retrieved the account"
         content:
           application/json:
             schema:
               "$ref": "#/components/schemas/AccountResponse"
       '404':
          description: The specified account was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                status: 404
                error: "Not Found"
                errorMessage: "Resource 3 not found."
                timestamp: "2026-06-29T15:25:37.5088930"
			   
  "/accounts/{accountId}/transactions":
    post:
      tags:
      - account-controller
      operationId: create
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionRequest"
        required: true
      responses:
        '201':
          description: Transaction successfully created. 
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionCreateReponse"
        '400':
          description: One or more fields failed validation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                status: 400
                error: "Validation Failed"
                fieldErrors:
                  amount: "must be greater than 0"
                  relatedAccountId: "must not be null"
                timestamp: "2026-06-29T15:25:37.5088930"                
				  
        '404':
          description: The specified account was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                status: 404
                error: "Not Found"
                errorMessage: "Resource 3 not found."
                timestamp: "2026-06-29T15:25:37.5088930"

components:
  schemas:
    
    AccountResponse:
      type: object
      required:
        - id
        - balance
      properties:
        id:
          type: integer
          format: int64
          example: 1
        balance:
          type: number
          example: 100.00
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/TransactionResponse"
		  
    TransactionResponse:
      type: object
      required:
        - transactionGroupId
        - amount
        - createdDate
      properties:
        transactionGroupId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        amount:
          type: number
          example: 100.00
        createdDate:
          type: string
          format: date-time
          example: "2026-06-28T23:01:59.187128-03:00"
    
    TransactionRequest:
      type: object
      required:
        - relatedAccountId
        - amount      
      properties:
        relatedAccountId:
          type: integer
          format: int64
          example: 2
        amount:
          type: number
          example: 100.00
    
    TransactionCreateReponse:
      type: object
      required:
        - transactionGroupId
        - amount
        - createdDate
      properties:
        transactionGroupId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        amount:
          type: number
          example: 100.00
        createdDate:
          type: string
          format: date-time
          example: "2026-06-28T23:01:59.187128-03:00"
		  
    ApiErrorResponse:
      type: object
      required:
        - status
        - error
        - timestamp
      properties:
        status:
          type: integer
          format: int32
          example: "404"        
        error:
          type: string
          example: "Not Found"
        errorMessage:
          type: string
          example: "Resource 3 not found."
        fieldErrors:
          type: object
          additionalProperties:
            type: string
          example:
            amount: "must be grater than 0"
            relatedAccountId: "must not be null"   
        timestamp:
          type: string
          format: date-time
          example: "2026-06-29T15:25:37.5088930"
